// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbF4GdS3klF0FV5CXwXxEnOxMsJRBWYag',
    appId: '1:881072867639:web:e689cd99271890965e32b2',
    messagingSenderId: '881072867639',
    projectId: 'wardrobe-f8e31',
    authDomain: 'wardrobe-f8e31.firebaseapp.com',
    databaseURL: 'https://wardrobe-f8e31-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wardrobe-f8e31.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyptq4_a3nnPmHqtj-lRHW7wlYtNrQOxc',
    appId: '1:881072867639:android:157413159eca0b9b5e32b2',
    messagingSenderId: '881072867639',
    projectId: 'wardrobe-f8e31',
    databaseURL: 'https://wardrobe-f8e31-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wardrobe-f8e31.appspot.com',
  );
}
